// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: lightswitch.proto

package lightswitchv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LightswitchService_AddLightSwitch_FullMethodName      = "/lightswitch.v1.LightswitchService/AddLightSwitch"
	LightswitchService_ToggleLightSwitch_FullMethodName   = "/lightswitch.v1.LightswitchService/ToggleLightSwitch"
	LightswitchService_GetLightSwitchStats_FullMethodName = "/lightswitch.v1.LightswitchService/GetLightSwitchStats"
	LightswitchService_GetAllLightSwitches_FullMethodName = "/lightswitch.v1.LightswitchService/GetAllLightSwitches"
	LightswitchService_GetLightSwitch_FullMethodName      = "/lightswitch.v1.LightswitchService/GetLightSwitch"
	LightswitchService_GetLightSwitchState_FullMethodName = "/lightswitch.v1.LightswitchService/GetLightSwitchState"
)

// LightswitchServiceClient is the client API for LightswitchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LightswitchServiceClient interface {
	AddLightSwitch(ctx context.Context, in *AddLightSwitchRequest, opts ...grpc.CallOption) (*AddLightSwitchResponse, error)
	ToggleLightSwitch(ctx context.Context, in *ToggleLightSwitchRequest, opts ...grpc.CallOption) (*ToggleLightSwitchResponse, error)
	GetLightSwitchStats(ctx context.Context, in *GetLightSwitchStatsRequest, opts ...grpc.CallOption) (*GetLightSwitchStatsResponse, error)
	GetAllLightSwitches(ctx context.Context, in *GetAllLightSwitchesRequest, opts ...grpc.CallOption) (*GetAllLightSwitchesResponse, error)
	GetLightSwitch(ctx context.Context, in *GetLightSwitchRequest, opts ...grpc.CallOption) (*GetLightSwitchResponse, error)
	GetLightSwitchState(ctx context.Context, in *GetLightSwitchStateRequest, opts ...grpc.CallOption) (*GetLightSwitchStateResponse, error)
}

type lightswitchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLightswitchServiceClient(cc grpc.ClientConnInterface) LightswitchServiceClient {
	return &lightswitchServiceClient{cc}
}

func (c *lightswitchServiceClient) AddLightSwitch(ctx context.Context, in *AddLightSwitchRequest, opts ...grpc.CallOption) (*AddLightSwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLightSwitchResponse)
	err := c.cc.Invoke(ctx, LightswitchService_AddLightSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightswitchServiceClient) ToggleLightSwitch(ctx context.Context, in *ToggleLightSwitchRequest, opts ...grpc.CallOption) (*ToggleLightSwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleLightSwitchResponse)
	err := c.cc.Invoke(ctx, LightswitchService_ToggleLightSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightswitchServiceClient) GetLightSwitchStats(ctx context.Context, in *GetLightSwitchStatsRequest, opts ...grpc.CallOption) (*GetLightSwitchStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLightSwitchStatsResponse)
	err := c.cc.Invoke(ctx, LightswitchService_GetLightSwitchStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightswitchServiceClient) GetAllLightSwitches(ctx context.Context, in *GetAllLightSwitchesRequest, opts ...grpc.CallOption) (*GetAllLightSwitchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllLightSwitchesResponse)
	err := c.cc.Invoke(ctx, LightswitchService_GetAllLightSwitches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightswitchServiceClient) GetLightSwitch(ctx context.Context, in *GetLightSwitchRequest, opts ...grpc.CallOption) (*GetLightSwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLightSwitchResponse)
	err := c.cc.Invoke(ctx, LightswitchService_GetLightSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightswitchServiceClient) GetLightSwitchState(ctx context.Context, in *GetLightSwitchStateRequest, opts ...grpc.CallOption) (*GetLightSwitchStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLightSwitchStateResponse)
	err := c.cc.Invoke(ctx, LightswitchService_GetLightSwitchState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LightswitchServiceServer is the server API for LightswitchService service.
// All implementations must embed UnimplementedLightswitchServiceServer
// for forward compatibility.
type LightswitchServiceServer interface {
	AddLightSwitch(context.Context, *AddLightSwitchRequest) (*AddLightSwitchResponse, error)
	ToggleLightSwitch(context.Context, *ToggleLightSwitchRequest) (*ToggleLightSwitchResponse, error)
	GetLightSwitchStats(context.Context, *GetLightSwitchStatsRequest) (*GetLightSwitchStatsResponse, error)
	GetAllLightSwitches(context.Context, *GetAllLightSwitchesRequest) (*GetAllLightSwitchesResponse, error)
	GetLightSwitch(context.Context, *GetLightSwitchRequest) (*GetLightSwitchResponse, error)
	GetLightSwitchState(context.Context, *GetLightSwitchStateRequest) (*GetLightSwitchStateResponse, error)
	mustEmbedUnimplementedLightswitchServiceServer()
}

// UnimplementedLightswitchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLightswitchServiceServer struct{}

func (UnimplementedLightswitchServiceServer) AddLightSwitch(context.Context, *AddLightSwitchRequest) (*AddLightSwitchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddLightSwitch not implemented")
}
func (UnimplementedLightswitchServiceServer) ToggleLightSwitch(context.Context, *ToggleLightSwitchRequest) (*ToggleLightSwitchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleLightSwitch not implemented")
}
func (UnimplementedLightswitchServiceServer) GetLightSwitchStats(context.Context, *GetLightSwitchStatsRequest) (*GetLightSwitchStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLightSwitchStats not implemented")
}
func (UnimplementedLightswitchServiceServer) GetAllLightSwitches(context.Context, *GetAllLightSwitchesRequest) (*GetAllLightSwitchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllLightSwitches not implemented")
}
func (UnimplementedLightswitchServiceServer) GetLightSwitch(context.Context, *GetLightSwitchRequest) (*GetLightSwitchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLightSwitch not implemented")
}
func (UnimplementedLightswitchServiceServer) GetLightSwitchState(context.Context, *GetLightSwitchStateRequest) (*GetLightSwitchStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLightSwitchState not implemented")
}
func (UnimplementedLightswitchServiceServer) mustEmbedUnimplementedLightswitchServiceServer() {}
func (UnimplementedLightswitchServiceServer) testEmbeddedByValue()                            {}

// UnsafeLightswitchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LightswitchServiceServer will
// result in compilation errors.
type UnsafeLightswitchServiceServer interface {
	mustEmbedUnimplementedLightswitchServiceServer()
}

func RegisterLightswitchServiceServer(s grpc.ServiceRegistrar, srv LightswitchServiceServer) {
	// If the following call panics, it indicates UnimplementedLightswitchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LightswitchService_ServiceDesc, srv)
}

func _LightswitchService_AddLightSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLightSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightswitchServiceServer).AddLightSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightswitchService_AddLightSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightswitchServiceServer).AddLightSwitch(ctx, req.(*AddLightSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightswitchService_ToggleLightSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleLightSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightswitchServiceServer).ToggleLightSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightswitchService_ToggleLightSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightswitchServiceServer).ToggleLightSwitch(ctx, req.(*ToggleLightSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightswitchService_GetLightSwitchStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLightSwitchStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightswitchServiceServer).GetLightSwitchStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightswitchService_GetLightSwitchStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightswitchServiceServer).GetLightSwitchStats(ctx, req.(*GetLightSwitchStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightswitchService_GetAllLightSwitches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllLightSwitchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightswitchServiceServer).GetAllLightSwitches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightswitchService_GetAllLightSwitches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightswitchServiceServer).GetAllLightSwitches(ctx, req.(*GetAllLightSwitchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightswitchService_GetLightSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLightSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightswitchServiceServer).GetLightSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightswitchService_GetLightSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightswitchServiceServer).GetLightSwitch(ctx, req.(*GetLightSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightswitchService_GetLightSwitchState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLightSwitchStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightswitchServiceServer).GetLightSwitchState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightswitchService_GetLightSwitchState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightswitchServiceServer).GetLightSwitchState(ctx, req.(*GetLightSwitchStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LightswitchService_ServiceDesc is the grpc.ServiceDesc for LightswitchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LightswitchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightswitch.v1.LightswitchService",
	HandlerType: (*LightswitchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLightSwitch",
			Handler:    _LightswitchService_AddLightSwitch_Handler,
		},
		{
			MethodName: "ToggleLightSwitch",
			Handler:    _LightswitchService_ToggleLightSwitch_Handler,
		},
		{
			MethodName: "GetLightSwitchStats",
			Handler:    _LightswitchService_GetLightSwitchStats_Handler,
		},
		{
			MethodName: "GetAllLightSwitches",
			Handler:    _LightswitchService_GetAllLightSwitches_Handler,
		},
		{
			MethodName: "GetLightSwitch",
			Handler:    _LightswitchService_GetLightSwitch_Handler,
		},
		{
			MethodName: "GetLightSwitchState",
			Handler:    _LightswitchService_GetLightSwitchState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lightswitch.proto",
}
