// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: lightswitch.proto

package lightswitchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LightSwitch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         bool                   `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightSwitch) Reset() {
	*x = LightSwitch{}
	mi := &file_lightswitch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightSwitch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightSwitch) ProtoMessage() {}

func (x *LightSwitch) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightSwitch.ProtoReflect.Descriptor instead.
func (*LightSwitch) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{0}
}

func (x *LightSwitch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LightSwitch) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *LightSwitch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddLightSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchName    string                 `protobuf:"bytes,1,opt,name=switch_name,json=switchName,proto3" json:"switch_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLightSwitchRequest) Reset() {
	*x = AddLightSwitchRequest{}
	mi := &file_lightswitch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLightSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLightSwitchRequest) ProtoMessage() {}

func (x *AddLightSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLightSwitchRequest.ProtoReflect.Descriptor instead.
func (*AddLightSwitchRequest) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{1}
}

func (x *AddLightSwitchRequest) GetSwitchName() string {
	if x != nil {
		return x.SwitchName
	}
	return ""
}

type AddLightSwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLightSwitchResponse) Reset() {
	*x = AddLightSwitchResponse{}
	mi := &file_lightswitch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLightSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLightSwitchResponse) ProtoMessage() {}

func (x *AddLightSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLightSwitchResponse.ProtoReflect.Descriptor instead.
func (*AddLightSwitchResponse) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{2}
}

func (x *AddLightSwitchResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ToggleLightSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLightSwitchRequest) Reset() {
	*x = ToggleLightSwitchRequest{}
	mi := &file_lightswitch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLightSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLightSwitchRequest) ProtoMessage() {}

func (x *ToggleLightSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLightSwitchRequest.ProtoReflect.Descriptor instead.
func (*ToggleLightSwitchRequest) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{3}
}

func (x *ToggleLightSwitchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ToggleLightSwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         bool                   `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLightSwitchResponse) Reset() {
	*x = ToggleLightSwitchResponse{}
	mi := &file_lightswitch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLightSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLightSwitchResponse) ProtoMessage() {}

func (x *ToggleLightSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLightSwitchResponse.ProtoReflect.Descriptor instead.
func (*ToggleLightSwitchResponse) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{4}
}

func (x *ToggleLightSwitchResponse) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

type GetLightSwitchStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLightSwitchStatsRequest) Reset() {
	*x = GetLightSwitchStatsRequest{}
	mi := &file_lightswitch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLightSwitchStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLightSwitchStatsRequest) ProtoMessage() {}

func (x *GetLightSwitchStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLightSwitchStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLightSwitchStatsRequest) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{5}
}

func (x *GetLightSwitchStatsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLightSwitchStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActiveSince     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=active_since,json=activeSince,proto3" json:"active_since,omitempty"`
	TotalActiveTime *durationpb.Duration   `protobuf:"bytes,3,opt,name=total_active_time,json=totalActiveTime,proto3" json:"total_active_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLightSwitchStatsResponse) Reset() {
	*x = GetLightSwitchStatsResponse{}
	mi := &file_lightswitch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLightSwitchStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLightSwitchStatsResponse) ProtoMessage() {}

func (x *GetLightSwitchStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLightSwitchStatsResponse.ProtoReflect.Descriptor instead.
func (*GetLightSwitchStatsResponse) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{6}
}

func (x *GetLightSwitchStatsResponse) GetActiveSince() *timestamppb.Timestamp {
	if x != nil {
		return x.ActiveSince
	}
	return nil
}

func (x *GetLightSwitchStatsResponse) GetTotalActiveTime() *durationpb.Duration {
	if x != nil {
		return x.TotalActiveTime
	}
	return nil
}

type GetAllLightSwitchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLightSwitchesRequest) Reset() {
	*x = GetAllLightSwitchesRequest{}
	mi := &file_lightswitch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLightSwitchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLightSwitchesRequest) ProtoMessage() {}

func (x *GetAllLightSwitchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLightSwitchesRequest.ProtoReflect.Descriptor instead.
func (*GetAllLightSwitchesRequest) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{7}
}

type GetAllLightSwitchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LightSwitches []*LightSwitch         `protobuf:"bytes,1,rep,name=light_switches,json=lightSwitches,proto3" json:"light_switches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLightSwitchesResponse) Reset() {
	*x = GetAllLightSwitchesResponse{}
	mi := &file_lightswitch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLightSwitchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLightSwitchesResponse) ProtoMessage() {}

func (x *GetAllLightSwitchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLightSwitchesResponse.ProtoReflect.Descriptor instead.
func (*GetAllLightSwitchesResponse) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllLightSwitchesResponse) GetLightSwitches() []*LightSwitch {
	if x != nil {
		return x.LightSwitches
	}
	return nil
}

type GetLightSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLightSwitchRequest) Reset() {
	*x = GetLightSwitchRequest{}
	mi := &file_lightswitch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLightSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLightSwitchRequest) ProtoMessage() {}

func (x *GetLightSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLightSwitchRequest.ProtoReflect.Descriptor instead.
func (*GetLightSwitchRequest) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{9}
}

func (x *GetLightSwitchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLightSwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LightSwitch   *LightSwitch           `protobuf:"bytes,1,opt,name=light_switch,json=lightSwitch,proto3" json:"light_switch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLightSwitchResponse) Reset() {
	*x = GetLightSwitchResponse{}
	mi := &file_lightswitch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLightSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLightSwitchResponse) ProtoMessage() {}

func (x *GetLightSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLightSwitchResponse.ProtoReflect.Descriptor instead.
func (*GetLightSwitchResponse) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{10}
}

func (x *GetLightSwitchResponse) GetLightSwitch() *LightSwitch {
	if x != nil {
		return x.LightSwitch
	}
	return nil
}

type GetLightSwitchStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLightSwitchStateRequest) Reset() {
	*x = GetLightSwitchStateRequest{}
	mi := &file_lightswitch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLightSwitchStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLightSwitchStateRequest) ProtoMessage() {}

func (x *GetLightSwitchStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLightSwitchStateRequest.ProtoReflect.Descriptor instead.
func (*GetLightSwitchStateRequest) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{11}
}

func (x *GetLightSwitchStateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLightSwitchStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         bool                   `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLightSwitchStateResponse) Reset() {
	*x = GetLightSwitchStateResponse{}
	mi := &file_lightswitch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLightSwitchStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLightSwitchStateResponse) ProtoMessage() {}

func (x *GetLightSwitchStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightswitch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLightSwitchStateResponse.ProtoReflect.Descriptor instead.
func (*GetLightSwitchStateResponse) Descriptor() ([]byte, []int) {
	return file_lightswitch_proto_rawDescGZIP(), []int{12}
}

func (x *GetLightSwitchStateResponse) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

var File_lightswitch_proto protoreflect.FileDescriptor

const file_lightswitch_proto_rawDesc = "" +
	"\n" +
	"\x11lightswitch.proto\x12\x0elightswitch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"G\n" +
	"\vLightSwitch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\bR\x05state\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"8\n" +
	"\x15AddLightSwitchRequest\x12\x1f\n" +
	"\vswitch_name\x18\x01 \x01(\tR\n" +
	"switchName\"(\n" +
	"\x16AddLightSwitchResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x18ToggleLightSwitchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x19ToggleLightSwitchResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\bR\x05state\",\n" +
	"\x1aGetLightSwitchStatsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa3\x01\n" +
	"\x1bGetLightSwitchStatsResponse\x12=\n" +
	"\factive_since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vactiveSince\x12E\n" +
	"\x11total_active_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0ftotalActiveTime\"\x1c\n" +
	"\x1aGetAllLightSwitchesRequest\"a\n" +
	"\x1bGetAllLightSwitchesResponse\x12B\n" +
	"\x0elight_switches\x18\x01 \x03(\v2\x1b.lightswitch.v1.LightSwitchR\rlightSwitches\"'\n" +
	"\x15GetLightSwitchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x16GetLightSwitchResponse\x12>\n" +
	"\flight_switch\x18\x01 \x01(\v2\x1b.lightswitch.v1.LightSwitchR\vlightSwitch\",\n" +
	"\x1aGetLightSwitchStateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x1bGetLightSwitchStateResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\bR\x05state2\x90\x05\n" +
	"\x12LightswitchService\x12_\n" +
	"\x0eAddLightSwitch\x12%.lightswitch.v1.AddLightSwitchRequest\x1a&.lightswitch.v1.AddLightSwitchResponse\x12h\n" +
	"\x11ToggleLightSwitch\x12(.lightswitch.v1.ToggleLightSwitchRequest\x1a).lightswitch.v1.ToggleLightSwitchResponse\x12n\n" +
	"\x13GetLightSwitchStats\x12*.lightswitch.v1.GetLightSwitchStatsRequest\x1a+.lightswitch.v1.GetLightSwitchStatsResponse\x12n\n" +
	"\x13GetAllLightSwitches\x12*.lightswitch.v1.GetAllLightSwitchesRequest\x1a+.lightswitch.v1.GetAllLightSwitchesResponse\x12_\n" +
	"\x0eGetLightSwitch\x12%.lightswitch.v1.GetLightSwitchRequest\x1a&.lightswitch.v1.GetLightSwitchResponse\x12n\n" +
	"\x13GetLightSwitchState\x12*.lightswitch.v1.GetLightSwitchStateRequest\x1a+.lightswitch.v1.GetLightSwitchStateResponseB$Z\"proto/lightswitch/v1;lightswitchv1b\x06proto3"

var (
	file_lightswitch_proto_rawDescOnce sync.Once
	file_lightswitch_proto_rawDescData []byte
)

func file_lightswitch_proto_rawDescGZIP() []byte {
	file_lightswitch_proto_rawDescOnce.Do(func() {
		file_lightswitch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lightswitch_proto_rawDesc), len(file_lightswitch_proto_rawDesc)))
	})
	return file_lightswitch_proto_rawDescData
}

var file_lightswitch_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_lightswitch_proto_goTypes = []any{
	(*LightSwitch)(nil),                 // 0: lightswitch.v1.LightSwitch
	(*AddLightSwitchRequest)(nil),       // 1: lightswitch.v1.AddLightSwitchRequest
	(*AddLightSwitchResponse)(nil),      // 2: lightswitch.v1.AddLightSwitchResponse
	(*ToggleLightSwitchRequest)(nil),    // 3: lightswitch.v1.ToggleLightSwitchRequest
	(*ToggleLightSwitchResponse)(nil),   // 4: lightswitch.v1.ToggleLightSwitchResponse
	(*GetLightSwitchStatsRequest)(nil),  // 5: lightswitch.v1.GetLightSwitchStatsRequest
	(*GetLightSwitchStatsResponse)(nil), // 6: lightswitch.v1.GetLightSwitchStatsResponse
	(*GetAllLightSwitchesRequest)(nil),  // 7: lightswitch.v1.GetAllLightSwitchesRequest
	(*GetAllLightSwitchesResponse)(nil), // 8: lightswitch.v1.GetAllLightSwitchesResponse
	(*GetLightSwitchRequest)(nil),       // 9: lightswitch.v1.GetLightSwitchRequest
	(*GetLightSwitchResponse)(nil),      // 10: lightswitch.v1.GetLightSwitchResponse
	(*GetLightSwitchStateRequest)(nil),  // 11: lightswitch.v1.GetLightSwitchStateRequest
	(*GetLightSwitchStateResponse)(nil), // 12: lightswitch.v1.GetLightSwitchStateResponse
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 14: google.protobuf.Duration
}
var file_lightswitch_proto_depIdxs = []int32{
	13, // 0: lightswitch.v1.GetLightSwitchStatsResponse.active_since:type_name -> google.protobuf.Timestamp
	14, // 1: lightswitch.v1.GetLightSwitchStatsResponse.total_active_time:type_name -> google.protobuf.Duration
	0,  // 2: lightswitch.v1.GetAllLightSwitchesResponse.light_switches:type_name -> lightswitch.v1.LightSwitch
	0,  // 3: lightswitch.v1.GetLightSwitchResponse.light_switch:type_name -> lightswitch.v1.LightSwitch
	1,  // 4: lightswitch.v1.LightswitchService.AddLightSwitch:input_type -> lightswitch.v1.AddLightSwitchRequest
	3,  // 5: lightswitch.v1.LightswitchService.ToggleLightSwitch:input_type -> lightswitch.v1.ToggleLightSwitchRequest
	5,  // 6: lightswitch.v1.LightswitchService.GetLightSwitchStats:input_type -> lightswitch.v1.GetLightSwitchStatsRequest
	7,  // 7: lightswitch.v1.LightswitchService.GetAllLightSwitches:input_type -> lightswitch.v1.GetAllLightSwitchesRequest
	9,  // 8: lightswitch.v1.LightswitchService.GetLightSwitch:input_type -> lightswitch.v1.GetLightSwitchRequest
	11, // 9: lightswitch.v1.LightswitchService.GetLightSwitchState:input_type -> lightswitch.v1.GetLightSwitchStateRequest
	2,  // 10: lightswitch.v1.LightswitchService.AddLightSwitch:output_type -> lightswitch.v1.AddLightSwitchResponse
	4,  // 11: lightswitch.v1.LightswitchService.ToggleLightSwitch:output_type -> lightswitch.v1.ToggleLightSwitchResponse
	6,  // 12: lightswitch.v1.LightswitchService.GetLightSwitchStats:output_type -> lightswitch.v1.GetLightSwitchStatsResponse
	8,  // 13: lightswitch.v1.LightswitchService.GetAllLightSwitches:output_type -> lightswitch.v1.GetAllLightSwitchesResponse
	10, // 14: lightswitch.v1.LightswitchService.GetLightSwitch:output_type -> lightswitch.v1.GetLightSwitchResponse
	12, // 15: lightswitch.v1.LightswitchService.GetLightSwitchState:output_type -> lightswitch.v1.GetLightSwitchStateResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_lightswitch_proto_init() }
func file_lightswitch_proto_init() {
	if File_lightswitch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lightswitch_proto_rawDesc), len(file_lightswitch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lightswitch_proto_goTypes,
		DependencyIndexes: file_lightswitch_proto_depIdxs,
		MessageInfos:      file_lightswitch_proto_msgTypes,
	}.Build()
	File_lightswitch_proto = out.File
	file_lightswitch_proto_goTypes = nil
	file_lightswitch_proto_depIdxs = nil
}
